name: EileMitWeile
description: EileMitWeile Flame game
version: 0.0.3
publish_to: none

environment:
  sdk: ^2.17.0
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter
  flame: 1.5.0
  yaml: ^3.1.0

flutter:
  assets:
    - assets/images/
    - pubspec.yaml