name: EileMitWeile
description: EileMitWeile Flame game
version: 0.0.5
publish_to: none

environment:
  sdk: ^2.17.0
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter
  flame: 1.5.0
  yaml: ^3.1.0

dev_dependencies:
  flutter_launcher_icons: "^0.11.0"

flutter:
  assets:
    - assets/images/
    - pubspec.yaml
  fonts:
    - family: Komika
      fonts:
        - asset: fonts/KOMIKAX_.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"